site_name: AWS Developer Associate Notes
theme:
  name: material
  palette:
    primary: light blue  # Header/navbar color
    accent: purple     # Links and accents
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
extra_css:
  - stylesheets/extra.css
  
